### ISSUE TITLE
Template variable error: 'dict object' has no attribute 'internet_loss_status'

### ISSUE THREAD

**Issue by holdestmade** [orbforge/addon-orb#11]
Getting this a lot in my logs since updating to 1.2.0

```
Logger: homeassistant.helpers.template
Source: helpers/template.py:2990
First occurred: 4:33:10 pm (152 occurrences)
Last logged: 4:45:41 pm

Template variable error: 'dict object' has no attribute 'internet_loss_status' when rendering '{{ value_json.orb_score.components.reliability_score.components.internet_loss_status.value | round(0) }}'
Template variable error: 'dict object' has no attribute 'internet_loss_status' when rendering '{{ (value_json.orb_score.components.reliability_score.components.internet_loss_status.value * 100) | round(0) }}'
```

**Comment by mignaulo** [comment]
Hi folks, I have an update.
Long story short, I removed the "High Packet Loss Proportion" entity from the addon for now - the error will go away, but I hope we'll be able to bring this back soon in a different manner. 

For more details, read on.

The Orb HA addon uses the summary which is accessible when you run `orb summary`. This provides a snapshot of the current state of data from the orb, it includes all the scores and the components used to calculate them. One of the component from the reliability score used to be the "High Packet Loss Proportion" (What portion of time we detected high packetloss. So to clarify, it was not the packetloss itself, it was just an indicator that there was high packetloss) 

We cleaned up our reliability methodology and this metric is no longer a component of the reliability. (Lag is the component and packetloss is already reflected as part of it. In some ways, we were including packetloss twice.) Unfortunately, when that was removed from reliability, a side effect is that it was removed from the summary as well, causing the errors. 

You might have seen the announcement of the Local API and the various datasets we have available as part of that: https://orb.net/blog/introducing-local-api
Ultimately, I suspect we'll want to have the Home Assistant addon start using the local API instead of the orb summary. When we do so, we'll have access to a lot more data and we'll be able to expose it all inside Home Assistant. I also think we'll be able to expose packetloss directly alongside our high packetloss proportion.
